workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        provisioning_profiles:
          - picgallery_appstore_profile

      vars:
        BUNDLE_ID: com.mk.picgallery
        API_HOST: https://api.picgallery.in

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS IPA
        script: |
          xcode-project use-profiles
          flutter build ipa --release \
            --dart-define=API_HOST=$API_HOST \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration