// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEL7ccWgswJP3w5LmRmFAcE_R2KW8qOMc',
    appId: '1:608395495309:web:5512a3195c0bab9c109fc4',
    messagingSenderId: '608395495309',
    projectId: 'picgallery-203',
    authDomain: 'picgallery-203.firebaseapp.com',
    storageBucket: 'picgallery-203.firebasestorage.app',
    measurementId: 'G-5PC8FM9B5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgpF9xptwMmow-o4a3071Pg9NS18wA0sQ',
    appId: '1:608395495309:android:57c54bfe02f25b1c109fc4',
    messagingSenderId: '608395495309',
    projectId: 'picgallery-203',
    storageBucket: 'picgallery-203.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6Q36z0O8uUwnTIQer7rNK6bnLRXCpJs',
    appId: '1:608395495309:ios:5c855c3e04b789a6109fc4',
    messagingSenderId: '608395495309',
    projectId: 'picgallery-203',
    storageBucket: 'picgallery-203.firebasestorage.app',
    iosClientId:
        '608395495309-l3tv61a947undm9uv344ecmfep8jsmtd.apps.googleusercontent.com',
    iosBundleId: 'com.mk.picgallery',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI6Q36z0O8uUwnTIQer7rNK6bnLRXCpJs',
    appId: '1:608395495309:ios:5c855c3e04b789a6109fc4',
    messagingSenderId: '608395495309',
    projectId: 'picgallery-203',
    storageBucket: 'picgallery-203.firebasestorage.app',
    iosClientId:
        '608395495309-l3tv61a947undm9uv344ecmfep8jsmtd.apps.googleusercontent.com',
    iosBundleId: 'com.mk.picgallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEL7ccWgswJP3w5LmRmFAcE_R2KW8qOMc',
    appId: '1:608395495309:web:5304c3386cb7afa0109fc4',
    messagingSenderId: '608395495309',
    projectId: 'picgallery-203',
    authDomain: 'picgallery-203.firebaseapp.com',
    storageBucket: 'picgallery-203.firebasestorage.app',
    measurementId: 'G-6WELYY0H7W',
  );
}
