"""Add collection_id to share links

Revision ID: 650240dd91f0
Revises: 5dae0dae3028
Create Date: 2026-09-13 15:08:53.844762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '650240dd91f0'
down_revision: Union[str, None] = '5dae0dae3028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('share_links', sa.Column('collection_id', sa.UUID(), nullable=True))
    except Exception:
        pass
    
    try:
        op.alter_column('share_links', 'album_id',
                   existing_type=sa.UUID(),
                   nullable=True)
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_share_links_collection_id'), 'share_links', ['collection_id'], unique=False)
    except Exception:
        pass
        
    try:
        op.create_foreign_key('fk_share_links_collection_id', 'share_links', 'gallery_collections', ['collection_id'], ['id'], ondelete='CASCADE')
    except Exception:
        pass
        
    try:
        op.create_check_constraint(
            'chk_share_link_target',
            'share_links',
            '(album_id IS NOT NULL AND collection_id IS NULL) OR (album_id IS NULL AND collection_id IS NOT NULL)'
        )
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_share_link_target', 'share_links', type_='check')
    op.drop_constraint('fk_share_links_collection_id', 'share_links', type_='foreignkey')
    op.drop_index(op.f('ix_share_links_collection_id'), table_name='share_links')
    op.alter_column('share_links', 'album_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('share_links', 'collection_id')
    # ### end Alembic commands ###
